### PR TITLE
[REF-2392] Expose next.config.js transpilePackages key

### LINKED ISSUE #2933: [REF-2392] Expose next.config.js `transpilePackages` key
**Describe the bug**
Some JS packages are not marked as `"type": "module"` in their `package.json`, so they cannot be directly imported in a nextjs app.

The workaround in this case is to add the packages to `transpilePackages` list in `next.config.js`, however this isn't exposed by reflex and it's kind of hard to hack.

Here's a workaround (in the main app module):

```python

def _hack_update_next_config():
    """This is a hack!!!"""
    from pathlib import Path

    next_config_file = Path(rx.constants.Dirs.WEB, rx.constants.Next.CONFIG_FILE)
    next_config = next_config_file.read_text()
    if "transpilePackages" not in next_config:
        next_config_file.write_text(
            next_config[:-3]
            + ", transpilePackages: ['@kitware/vtk.js', 'react-vtk-js']};"
        )


_hack_update_next_config()
```

But that sort of sucks.

<sub>[REF-2392](https://linear.app/reflex-dev/issue/REF-2392/expose-nextconfigjs-transpilepackages-key)</sub>

### PR DESCRIPTION
**Pull request by masenf**
Add `transpile_packages` knob to reflex Config object to escape hatch for packages that need to be transpiled first.

Why not include this in the ImportVar mechanism? Because it's very nextjs specific, and not needed in the general case, so I didn't want to plumb it through the internals of the reflex Component system.

Fix #2933

## Why

Some libraries don't work with nextjs out of the box, like [`react-tweet`](https://react-tweet.vercel.app)

```python
import reflex as rx


class Tweet(rx.Component):
    tag = "Tweet"
    library = "react-tweet"


@rx.page()
def index():
    return Tweet.create(id="1775605401100366012")


app = rx.App()
```

### Before

```
./node_modules/react-tweet/dist/twitter-theme/theme.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/react-tweet/dist/twitter-theme/tweet-container.js
```

image

### After

Add `transpile_packages: list[str] = ["react-tweet"]` to Component definition.

```python
class Tweet(rx.Component):
    tag = "Tweet"
    library = "react-tweet"
    transpile_packages: list[str] = ["react-tweet"]
```

image

### CODE REVIEW

**Review by Lendemor — APPROVED** [review]

**Review by picklelo — CHANGES_REQUESTED** [review]
Is it possible to make this a field within `rx.Component`? Then during compilation we can detect if any components need transpired packages and just add it there.

That way if someone wraps `react-tweet` it will work out of the box without the end user having to modify their `rxconfig`.

**Comment by masenf** [comment]
> Is it possible to make this a field within `rx.Component`?

That's what I was trying to do initially, but often you need to transpile something in lib_dependencies and those are just strings.

I thought about adding another instance var like `transpile_dependencies` that worked like lib_dependencies, but added them to this list in next.config.js.

Then the issue was, next.config.js is written out during init before anything has been compiled. I think it might be possible to move that step to compilation as well, but that was a larger change to get the needed functionality.

Finally, since package transpilation is kind of a next-specific thing, I didn't know if it actually made sense to first-class it in the component.

Upon further reflection though, if we want this to actually be usable for third party components installed from pip, I think we MUST make it part of the Component definition so downstream users don't need to also configure their rxconfig.

Moving to draft. I'll make the changes to move the next config stuff to a later stage in the compile.

If you have input on what the API should look like, please post it here @picklelo @martinxu9

**Comment by masenf** [comment]
@picklelo Latest commit implements this as a field on Component. It was definitely more plumbing, but thanks for calling this out, it was the right move.

**Review by picklelo — APPROVED** [review]
working well for me

**Pull request merged**
