### PR TITLE
[REF-2586] Pass child event_trigger through DebounceInput

### LINKED ISSUE #3060: [REF-2586] on_key_down not called for input wrapped in a debounce_input.
Greetings all. Updating an app from v0.3.2 to the latest I found that on_key_down is not called for an input wrapped in a debounce_input. This shows how to reproduce, and a range of commits where the problem began.

## Install An Environment With v0.3.2 And Run A Minimal Test To Show The Original Behaviour

Python and Reflex Versions: shown below.
OS: Arch Linux with all latest updates.
Browser: Chrome 123

```bash
conda deactivate
conda env remove -yn test
conda create -yqn test python=3.12
conda activate test

mkdir test &&
cd test &&
git clone git@github.com:reflex-dev/reflex.git &&
cd reflex &&
git checkout v0.3.2 &&
cd .. &&
pip install -e reflex &&
reflex init # Accept blank template.
```

Replace the content of `test/test.py` with this...

```python
import reflex as rx


class State(rx.State):
    something: str = ""

    def on_key_down(self, key):
        print(key)


def index() -> rx.Component:
    return rx.box(
        rx.text(f"Reflex version: {rx.constants.Reflex.VERSION}"),
        rx.debounce_input(
            rx.input(
                on_change=State.set_something,
                on_key_down=State.on_key_down,
            ),
            debounce_timeout=250,
            value=State.something,
        ),
    )


app = rx.App()
app.add_page(index)
app.compile()
```

```bash
reflex init && reflex run
```

Type in the input, the console shows the keys being printed.

## Update To The Latest To Show It Not Working That Way Anymore

```bash
^C
cd reflex &&
git checkout v0.4.7 &&
cd .. &&
pip install -e reflex &&
reflex init && reflex run
```

Type in the input, the console **no longer** shows the keys being printed.

## Find The Version Where The Change Happened

```bash
^C
cd reflex &&
git checkout <different versions> &&
cd .. &&
pip install -e reflex &&
reflex init && reflex run
```

Until finding that v0.3.4 works, v0.3.5 has the issue.

## Narrow Down To A Range Of Commits Where The Problem Was Introduced

The problem is somewhere between these two commits.

```plain
0c55723d [Tue Nov 28 18:04:07 2023] (HEAD, tag: bad) [REF-1158] Move chakra-only deps to chakra lib (#2171) [GitHub]
ee87e62e [Tue Nov 28 12:17:53 2023] [REF-1035] Track ComputedVar dependency per class (#2067) [GitHub]
626357ed [Tue Nov 28 12:09:41 2023] Memoize markdown component_map (#2219) [GitHub]
065b1b88 [Tue Nov 28 11:59:35 2023] Add index on tabs (#2225) [GitHub]
527437cf [Tue Nov 28 10:05:59 2023] [REF-144] Add context in each component to prevent rerenders (#2198) [GitHub]
ed5b3818 [Tue Nov 28 08:04:55 2023] (tag: good) update removal version of deprecated features (#2224) [GitHub]
```

## See Why It Is Somehow Related To Debounce

Comment out the debounce like this, while running a version that doesn't work.

```python
def index() -> rx.Component:
    return rx.box(
        rx.text(f"Reflex version: {rx.constants.Reflex.VERSION}"),
        # rx.debounce_input(
            rx.input(
                on_change=State.set_something,
                on_key_down=State.on_key_down,
            # ),
            # debounce_timeout=250,
            # value=State.something,
        ),
    )
```

Type in the input, the console shows the keys being printed.

Without the debounce it works in all versions.

## But Another Wrinkle Even Without The Debounce

Uncomment the `value=`, so that the input is updated when `State.something` is updated.

```python
def index() -> rx.Component:
    return rx.box(
        rx.text(f"Reflex version: {rx.constants.Reflex.VERSION}"),
        # rx.debounce_input(
            rx.input(
                on_change=State.set_something,
                on_key_down=State.on_key_down,
            # ),
            # debounce_timeout=250,
            value=State.something,
        ),
    )
```

Type in the input, the console again **doesn't** show the keys being printed.

<sub>[REF-2586](https://linear.app/reflex-dev/issue/REF-2586/on-key-down-not-called-for-input-wrapped-in-a-debounce-input)</sub>

### PR DESCRIPTION
**Pull request by masenf**
Fix #3060

## Sample Code

```python
import reflex as rx


class State(rx.State):
    v: str = ""

    def handle_on_key_down(self, key):
        print(key)

    def set_v(self, value):
        self.v = value
        print(self.v)


def index() -> rx.Component:
    return rx.center(
        rx.input(
            value=State.v,
            on_change=State.set_v,
            on_key_down=State.handle_on_key_down,
        ),
    )


app = rx.App()
app.add_page(index)
```

### CODE REVIEW

**Review by Lendemor — APPROVED** [review]

**Comment by nevdelap** [comment]
Why does the sample code not have a debounce?

**Comment by masenf** [comment]
@nevdelap DebounceInput is applied automatically for any text field that defines `on_change` and `value` together. It's implicit.

Is the fix not working in your explicitly debounced input case?

**Comment by nevdelap** [comment]
Ah, sweet. No, I just didn't no it was explicit. Thank you!

**Comment by nevdelap** [comment]
Hi @masenf. :wave: 

I thought this was working for me, and now I'm finding it is not. With a freshly `reflex init`ed test project, and your example code I've added the `"kd:"` in the `on_key_down` to be sure, and it is not being printed.

```
import reflex as rx


class State(rx.State):
    v: str = ""

    def handle_on_key_down(self, key):
        print("kd:", key)

    def set_v(self, value):
        self.v = value
        print(self.v)


def index() -> rx.Component:
    return rx.center(
        rx.input(
            value=State.v,
            on_change=State.set_v,
            on_key_down=State.handle_on_key_down,
        ),
    )


app = rx.App()
app.add_page(index)
```

Output as I've typed `sdfsdfccc`.

```
Compiling: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 13/13 0:00:00
sdfsdf
sdfsdfccc
```

Commenting out the `on_change`, `# on_change=State.set_v,`, `on_key_down` starts getting called.

```
Compiling: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 13/13 0:00:00
kd: q
kd: w
kd: d
kd: s
kd: a
kd: d
```

```
> python --version
Python 3.12.3
> reflex --version
0.4.8.post1
> google-chrome-stable --version
Google Chrome 124.0.6367.60
```

**Comment by masenf** [comment]
@nevdelap this PR is in 0.4.9, which was released about 90 minutes ago

**Comment by nevdelap** [comment]
Updated and it's all working as expected. Thanks again. I should have realised what was going on. :heart:

**Pull request merged**
