### PR TITLE
DRAFT PR - Added code for computed backend vars

### PR DESCRIPTION
**Pull request by wassafshahzad**
### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/reflex-dev/reflex/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/reflex-dev/reflex/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### New Feature Submission:

- [x] Does your submission pass the tests? 
- [x] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

## Description
Allow computed vars to be converted to backend vars by appending "_"

###Note

### CODE REVIEW

**Comment by benedikt-bartscher** [comment]
Hi @wassafshahzad thank you for this awesome idea!
If my PR #2534 gets merged, we would need to coordinate our PRs. @masenf what do you think? Should this PR be based on #2534 ?

**Comment by wassafshahzad** [comment]
> Hi @wassafshahzad thank you for this awesome idea! If my PR #2534 gets merged, we would need to coordinate our PRs. @masenf what do you think? Should this PR be based on #2534 ?

I can rebase to main after your merge.

**Review by masenf — COMMENTED** [review]
This change sends the backend computed vars to the frontend for some reason. The backend computed vars should never be available for direct rendering

```python
import random
import reflex as rx

class State(rx.State):
    @rx.var
    def _be_computed_be(self):
        return random.random()


def index() -> rx.Component:
    return rx.vstack(
        rx.heading(f"Computed BE {State._be_computed_be}"),
        spacing="1.5em",
        font_size="2em",
        padding_top="10%",
    )


app = rx.App()
app.add_page(index)
```

**Comment by wassafshahzad** [comment]
@masenf 

Just wanted to confirm one thing, The backend var should also not be available for render and this code should fail ,right? If i understand correctly 
```
import random
import reflex as rx

class State(rx.State):

    _private: str = "Should work ?"

    @rx.var
    def _be_computed_be(self):
        return random.random()


def index() -> rx.Component:
    return rx.vstack(
        rx.heading(f"Computed BE {State._private}"),
        spacing="1.5em",
        font_size="2em",
        padding_top="10%",
    )


app = rx.App()
app.add_page(index)
```

**Comment by picklelo** [comment]
@wassafshahzad Yes the backend vars should not be accessible to the frontend

**Review by masenf — COMMENTED** [review]
If you re-merge from origin/main and fix the conflicts in `state.py` i think we can take this one. We don't have to worry so much about what happens if someone tries to use a backend var in their frontend code; it will kind of work, not really update, and that's not a regression, so lets just try to focus on getting this one through.

**Review by masenf — APPROVED** [review]

**Pull request merged**
