### PR TITLE
exec: print the URL, not the address the server binds to

### PR DESCRIPTION
**Pull request by masenf**
Fix: REF-641

### CODE REVIEW

**Comment by tgberkeley** [comment]
Looks great. Works for me again.

**Review by tgberkeley — APPROVED** [review]

**Comment by nevdelap** [comment]
Doesn't that make it print that is running on localhost when it is bound to 0.0.0.0 again?

**Comment by masenf** [comment]
@nevdelap Neither is technically "correct". But formatting the bind address, `0.0.0.0`, as a URL and displaying it results in a link that doesn't work when clicked.

With this change, the user can sometimes click on the `http://localhost:8000/whatever` link and have it actually take them to their app (if they are opening a browser on the same machine as the server).

Not sure what the right answer here is and happy to hear suggestions... but we had complaints from users that the link displayed did not work, so I would consider that a bug.

Users can pass `--loglevel debug` if they want to see the bind address or it could be printed separately (maybe just print that entire line from the next server instead of regexing parts out?), but it can't replace the (sometimes) working URL to the app.

**Comment by nevdelap** [comment]
I wonder if it should just display the whole line rather than picking out one or the other piece.

**Pull request merged**
