### PR TITLE
docs: fixed wrapping react link

### LINKED ISSUE #2096: Broken link of wrapping react in readme file
**Describe the bug**
The link to wrapping react in readme file is broken.

**To Reproduce**
 - Code/Link to Repo:
 - Go to Readme file
 - Go to Reflex UI section 
 - Click on 

> it's easy to [create your own components](https://reflex.dev/docs/advanced-guide/wrapping-react).

**Expected behavior**
The link should not be broken and redirect correctly.

**Screenshots**
Screenshot 2023-10-31 221146

**Specifics (please complete the following information):**
 - Python Version:
 - Reflex Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

### PR DESCRIPTION
**Pull request by Shreyas0410**
### All Submissions:

- [X] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/reflex-dev/reflex/blob/main/CONTRIBUTING.md) file?
- [X] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/reflex-dev/reflex/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

Fixes #2096 

Fixed the wrapping react link. 

Screenshot 2023-10-31 221458

### CODE REVIEW

**Review by masenf — APPROVED** [review]
Thanks for the fix

**Comment by masenf** [comment]
@Shreyas0410 do you mind also making this correction in the translated README?

**Review by Lendemor — DISMISSED** [review]

**Comment by Shreyas0410** [comment]
@masenf ok i will do it.

**Review by masenf — APPROVED** [review]
Awesome, thanks so much for the contribution

**Pull request merged**
