### PR TITLE
Support python 3.13

### PR DESCRIPTION
**Pull request by Lendemor**
Upstream issue is blocking support for Windows psycopg2.

Reflex is already technically usable for 3.13, we just won't have the CI to guarantee it or catch issues.

Converted to Draft until upstream is fixed.

### CODE REVIEW

**Review by picklelo — DISMISSED** [review]

**Comment by adhami3310** [comment]
blocked on https://github.com/psycopg/psycopg2/issues/1736 which is blocked on https://github.com/appveyor/ci/issues/3927

**Comment by benedikt-bartscher** [comment]
@Lendemor this is great!
btw, just to let you know: we are using reflex with python3.13 and psycopg3 for a while now, without any issues

**Comment by Lendemor** [comment]
> @Lendemor this is great! btw, just to let you know: we are using reflex with python3.13 and psycopg3 for a while now, without any issues

Thanks for that feedback. Maybe we can go ahead with this then.

**Review by adhami3310 — APPROVED** [review]

**Review by masenf — DISMISSED** [review]
works for me. was able to re-deploy https://rx-shout.mooo.com with py3.13, 0.6.6a2, and  psycopg3 👍

**Review by masenf — APPROVED** [review]

**Pull request merged**
