### PR TITLE
Use tailwind typography plugin by default

### PR DESCRIPTION
**Pull request by minimav**
This PR addresses #1529 to make the HTML component display tags correctly by default via the Tailwind typography plugin as suggested on the issue itself and using the `prose` class as mentioned [here](https://github.com/reflex-dev/reflex/issues/613#issuecomment-2080271098).

Example of this working:

Screenshot 2024-06-29 at 15 28 19

via this:

Screenshot 2024-06-29 at 15 28 37

-------

### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/reflex-dev/reflex/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/reflex-dev/reflex/pulls ) for the desired changed?

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### New Feature Submission:

- [x] Does your submission pass the tests? 
- [x] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by Lendemor** [comment]
I don't have an issue about the code itself, I'm just not sure if we should have the `tailwindcss/typography` as a default for every project, rather than enabling it when rx.html is used.

**Comment by masenf** [comment]
@Lendemor is there a perceived downside to bringing in the typography plugin for every project? Slightly large download size perhaps, but i think in deploy/prod mode the extra classes will be pruned out if `prose` is not actually used anywhere.

**Comment by Lendemor** [comment]
> @Lendemor is there a perceived downside to bringing in the typography plugin for every project? Slightly large download size perhaps, but i think in deploy/prod mode the extra classes will be pruned out if `prose` is not actually used anywhere.

Probably nothing big, I just remembered some users disabling tailwind in their projects (we had it included as default before, then we made it optional at some point) because it was conflicting with some others stuff they were using I think.

If we enable it forcefully again, it might break these users apps? I'm not sure how many users this is tho, so maybe it's not a big deal.

**Comment by masenf** [comment]
> If we enable it forcefully again

If user sets `tailwind=None` in their config, then they will not get the plugins either, so i think it's safe

**Review by adhami3310 — APPROVED** [review]
Sorry for sleeping on it 😅

**Pull request merged**
