### PR TITLE
Added dynamic convenience methods and remove manual redifinitions in __init.py__

### PR DESCRIPTION
**Pull request by y9rabbito**
This PR is according to the issue #1865, autogenerate convenience methods for all the components.

### CODE REVIEW

**Review by masenf — COMMENTED** [review]
I pushed a change to get the tests passing, but I'm not sure this is actually what we want, as it seems to break auto-complete in the IDE. Typing `rx.button(` for example no longer shows the correct function/type signatures with this change.

**Review by y9rabbito — COMMENTED** [review]
Imports the to_snake_case(name), defined in reflex_utils_format, and also delete import of utils

**Comment by Billa05** [comment]
> I pushed a change to get the tests passing, but I'm not sure this is actually what we want, as it seems to break auto-complete in the IDE. Typing `rx.button(` for example no longer shows the correct function/type signatures with this change.

 maybe it is better to keep manual redefinitions to maintain a good developer experience

**Comment by masenf** [comment]
We'll keep the static definitions for now for better type checking and IDE integration. In the future we will look at generating the component `__init__.py` helpers/wrappers similarly to the `.pyi` files that are already generated.

**Pull request closed without merging**
