### PR TITLE
add typed dict type checking

### PR DESCRIPTION
**Pull request by adhami3310**

### CODE REVIEW

**Comment by adhami3310** [comment]
So this also included some changes in the check of var values being of the correct type. This has uncovered some issues in reflex-web. I will make a PR there and update this one once that has merged. @masenf

**Comment by adhami3310** [comment]
blocked on #1079

**Comment by benedikt-bartscher** [comment]
> blocked on #1079

Links to wrong repo
https://github.com/reflex-dev/reflex-web/pull/1079

**Comment by adhami3310** [comment]
> Links to wrong repo
ooops, defn not blocked by something that merged years ago :sweat_smile:

**Comment by adhami3310** [comment]
is ready for merge, although we should really fix `check_latest_node`

**Pull request merged**
