### PR TITLE
disable prose by default for rx.html

### PR DESCRIPTION
**Pull request by adhami3310**

### CODE REVIEW

**Review by Lendemor — DISMISSED** [review]

**Review by masenf — COMMENTED** [review]
what is the motivation for this change?

**Comment by adhami3310** [comment]
> what is the motivation for this change?

some people (carlos) rely on existing html code that looks very different now, so we're preserving existing behavior.

additionally, it reflects the behavior of doing `rx.el.h1` for example, which is unstyled by default.

**Comment by masenf** [comment]
so this partly reverts the change brought in by #3593

but looking at that PR closer i see that it doesnt do anything with `rx.markdown` but the original bug it was supposed to be fixing specifically mentions markdown and html being affected (maybe markdown got fixed since then).

i guess what im getting at is why not just revert that entire PR? this new styled prop is confusingly named IMO and not particularly discoverable.

**Comment by adhami3310** [comment]
> not just revert that entire PR? this new styled prop is confusingly named IMO and not particularly discoverable

good question! i pose that some might find it convenient to bring back that property, but also, they could do `class_name="prose"` to do the same behavior, making this essentially uesless so :shrug: .

**Review by masenf — APPROVED** [review]

**Pull request merged**
