### PR TITLE
add InputLeftElement, InputRightElement

### PR DESCRIPTION
**Pull request by YUNGU23**
### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### New Feature Submission:

- [ ] Does your submission pass the tests? 
- [x] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.

    b. Describe your changes.

    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by YUNGU23** [comment]
add InputLeftElement, InputRightElement

**Comment by Alek99** [comment]
Looks good see the build I think you just need to run formatting and listing scripts

**Comment by YUNGU23** [comment]
Thanks, Alex. Regrettably, my pull request was rejected due to my oversight of not including an empty line at the end of the code. To address this issue, I need to make the required modifications by adding the missing newline and subsequently submit a new pull request. Am I correct in my understanding?

In terms of formatting, I utilized the "Format Document With -> Python" option in VSCode. And for listing scripts, I installed pylint. However, when running pylint for code analysis, it yielded a rating of 0.86/10. Pylint suggested that I should redefine built-in functions and that import aliases should not rename the original package. I'm unsure about what steps to take next, and I'm feeling confused.

**Comment by Alek99** [comment]
I'll message you on discord but I think if you run `poetry run ruff check .` make another commit it should resolve that error

**Comment by Alek99** [comment]
I think you just need to rebase this because we switch ed to reflex and we can merge it in

**Comment by YUNGU23** [comment]
> I think you just need to rebase this because we switch ed to reflex and we can merge it in

It seems you added it. right?

**Comment by masenf** [comment]
Added as part of #1335

**Pull request closed without merging**
