### PR TITLE
[Fix #1346] Support event handler to call browser-side javascript

### LINKED ISSUE #1346: Set an event handler for a button so that it will call browser-side JavaScript code.
**Describe the bug**

### Feature 

I know how to write simple html/javascript code and put them in the WebView of mobile 
so that iOS native apps and Android native apps can communicate to the webpage in the WebView. 

I am evaluating an outsourcing case to make iOS/Android mobile app. 
I will put the reflex web app in the WebView in the iOS/Android mobile app. 

- Scenario 1 
Still can show ID as QRCode from the native app when mobile's internet  is offline 
When mobile is in the offline status, there is a button in the web app, and the user can click it 
to trigger the function in the iOS/android native app to show the QRCode for some string.  
This string will be some special ID of a VIP member in the group.  
We hope they can still show their ID to check even if their mobile cannot connect to the internet.

- Scenario 2
mobile's internet is online in this scenario. 
When the user wants to scan QRCode, they can click the button in the web app. 
Click this button will call browser-side javascript code to trigger iOS/android native app
to show the camera to scan QRCode. 

When iOS/Android native app gets the scan result as a string from QRCode, 
it can send the string to the web app in the WebView by the API route. 

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version:
 - Reflex Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

### PR DESCRIPTION
**Pull request by milochen0418**
### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

### New Feature Submission:

- [x] Does your submission pass the tests? 
- [x] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully ran tests with your changes locally?

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.
Support to call browser-side javascript function from an event handler. 
    b. Describe your changes.
Just add a special event
    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

closes #1346

The following is the running example code that can match the latest source code of this Pull Request
- https://github.com/milochen0418/reflex-call-browser-js

```python
import reflex as rx

javascript_functions = """<script>
function test_func_1(jobj) {
  console.log('My name is ' + jobj.myname + ' and my action is ' + jobj.myaction);
}
function test_func_2(jobj) {
  console.log('My course is ' + jobj.mycourse + ' and my score is ' + jobj.myscore);
}
</script>"""

def scripts(js=javascript_functions):
    return rx.box(rx.html(js))

class State(rx.State):
    def btn_test_func_1(self):
        dobj = {"__func__":"test_func_1", "myname":"Milo", "myaction":"Jump"}
        yield rx.browsercall(dobj)
    def btn_test_func_2(self):
        dobj = {"__func__":"test_func_2", "mycourse":"Math", "myscore":99}
        yield rx.browsercall(dobj)
    def btn_test_func_3(self):
        dobj = {"__func__":"test_func_3", "mycourse":"Math", "myscore":"99"}
        yield rx.browsercall(dobj)

def index() -> rx.Component:
    return rx.fragment(
        rx.center(
            rx.vstack(
                rx.heading("Call Browser-Side JavaScript"),
                rx.button("browser call test_func_1", on_click=State.btn_test_func_1),
                rx.button("browser call test_func_2", on_click=State.btn_test_func_2),
                rx.button("browser call test_func_3", on_click=State.btn_test_func_3),
            ),
        ),
    )

app = rx.App(state=State)
app.add_page(index, script_tags = [scripts()] )
app.compile()
```

### CODE REVIEW

**Comment by milochen0418** [comment]
This part should move somewhere as the default javascript code.  
So that the user doesn't need to know where it is and it just dispatches to 
the javascript function that we set in script_tags. 
```javascript
function dispatch(jobj) {
  var func = jobj.__func__;
  eval(func + '(jobj)');
}

browsercall = function(msg) {
    try {
        var jobj = JSON.parse(msg);
        dispatch(jobj);
    } catch(e) {
        console.log(e.name);
        console.log(e.message);
    }
};
```

**Comment by milochen0418** [comment]
When webapp run in the network, the client-side javascript cannot run in order. 

I think I what can improve are 
(1) add a event queue for client-side and run client-side javascript in order by the event queue. 
(2) Support to run pure javascript code.

**Comment by masenf** [comment]
@milochen0418 do we still need this patch with the addition of `rx.script` and `rx.client_side`?

**Comment by masenf** [comment]
It finally hit me tonight that `rx.client_side` as currently implemented is not sufficient for this use case as it cannot be `yield`/`return` from a backend `EventHandler`. I think we can truly support the use case in this PR with a few tweaks.

**Pull request closed without merging**
