### PR TITLE
[REF-2265] ComponentState: scaffold for copying State per Component instance

### PR DESCRIPTION
**Pull request by masenf**
Define a base ComponentState which can be used to easily create copies of the given State definition (Vars and EventHandlers) that are tied to a particular instance of a Component (returned by get_component)

## Sample Code

```python
import reflex as rx


class Counter(rx.ComponentState):
    count: int = 0

    def increment(self):
        self.count += 1

    def decrement(self):
        self.count -= 1

    @classmethod
    def get_component(cls, *children, **props) -> rx.Component:
        return rx.vstack(
            *children,
            rx.hstack(
                rx.button(
                    "Decrement",
                    bg="#fef2f2",
                    color="#b91c1c",
                    radius="large",
                    on_click=cls.decrement,
                ),
                rx.heading(cls.count, font_size=props.pop("font_size", "2em")),
                rx.button(
                    "Increment",
                    bg="#ecfdf5",
                    color="#047857",
                    radius="large",
                    on_click=cls.increment,
                ),
                spacing=props.pop("spacing", "1"),
            ),
            **props,
        )


counter = Counter.create


def index():
    counter1 = counter(id="c1")
    return rx.vstack(
        counter1,
        counter(rx.center(rx.heading("Counter 2"), width="100%"), margin="5px", border="1px solid black"),
        counter(),
        counter(),
        rx.button("Inc c1", on_click=counter1.State.increment),
    )


app = rx.App()
app.add_page(index)
```

https://github.com/reflex-dev/reflex/assets/1524005/cdb2b55f-e158-48a8-90d4-29b4c989ffda

### CODE REVIEW

**Review by picklelo — COMMENTED** [review]
Everything is working great for me.

One note: for my chat component I needed to override the `create` method in order to set a property on my component state:

```python
class Chat(rx.ComponentState):
    """A chat component with state."""

    # The full chat history.
    messages: list[dict[str, str]] = [{
        "role": "system",
        "content": "You are a friendly chatbot named Reflex. Respond in markdown."
    }]

    # Whether we are processing the question.
    processing: bool = False

    @classmethod
    def create(self, process, **props):
        component = super().create(**props)
        component.State.process = process
        return component

    @classmethod
    def get_component(cls, **props) -> rx.Component:
        return rx.vstack(
        ...
```

It may be cleaner to move everything into the `create` method (and do the thing you suggested of having some metaclass around the `create` that does the additional processing around the component creation.

We can also revisit this improvement later, I think most people won't be modifying the state class (though it may be common if they want to write their own hooks/handlers)

**Review by picklelo — APPROVED** [review]
Working well with my chat component!

**Review by martinxu9 — COMMENTED** [review]
so what does it look like for a component (that's wrapping react) now?

**Comment by martinxu9** [comment]
> so what does it look like for a component (that's wrapping react) now?

never mind I confused myself for a second

**Review by martinxu9 — APPROVED** [review]

**Pull request merged**
