### PR TITLE
Reconnection Logic

### PR DESCRIPTION
**Pull request by Yummy-Yums**
### All Submissions:

- [ ] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/reflex-dev/reflex/blob/main/CONTRIBUTING.md) file?
- [ ] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/reflex-dev/reflex/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### New Feature Submission:

- [ ] Does your submission pass the tests? 
- [ ] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.

    b. Describe your changes.

    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by Yummy-Yums** [comment]
closes #2728

**Comment by Yummy-Yums** [comment]
@Alek99 i tested it by running _reflex run --frontend-only_ to simulate a broken cxn and _reflex run_ just by checking if user is connected

image

**Comment by picklelo** [comment]
@Yummy-Yums in your testing, do you see the error occur when we don't have your changes? I'm trying to test this out - it seems to be working, but I can't reproduce the broken case locally to understand if the fix is working.

**Comment by Yummy-Yums** [comment]
@picklelo I ran _reflex run --frontend-only_ to simulate a "broken cxn" to test, but realized that it simulates a "no cxn" since websockets need to be established for both parties, for even a broken cxn to happen. Also, based on this error (pic below) in the reflex docs in prod (i just disrupt my internet cxn)

image



@Alek99 can i get steps to repro this issue below ? Thanks 

image

**Review by masenf — APPROVED** [review]

**Comment by picklelo** [comment]
@Yummy-Yums I believe this issue only happens when the tab has been open for a really long time (like days potentially) so it's hard to test for. I think your code should work, we will see when we redeploy the website whether people still run into this issue. Thanks for the contribution!

**Pull request merged**
