### PR TITLE
[REF-2132]Deprecate Admin Dashboard

### PR DESCRIPTION
**Pull request by ElijahAhianyo**
### All Submissions:

- [ ] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/reflex-dev/reflex/blob/main/CONTRIBUTING.md) file?
- [ ] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/reflex-dev/reflex/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### New Feature Submission:

- [ ] Does your submission pass the tests? 
- [ ] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.

    b. Describe your changes.

    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by thphuc** [comment]
Hi @ElijahAhianyo May I know why we decided to deprecate the Admin Dashboard?

**Comment by Alek99** [comment]
> Hi @ElijahAhianyo May I know why we decided to deprecate the Admin Dashboard?

Is this a feature you are currently using? It wasn't documented previously, so we were not sure how many people are using it.

 In general we have been trying to slim down your dependencies to avoid conflicts with other packages, this was part of that.

**Comment by mandarvaze** [comment]
Admin Dashboard maybe a good feature to have (even if optional)
I would prefer that it be documented, rather than deprecated 😄

**Comment by picklelo** [comment]
@mandarvaze our plan was to make our own using Reflex in the future, but we can keep this one for now until we have that.

@ElijahAhianyo I'll close this PR, let's add docs for now for this.

**Pull request closed without merging**
