### PR TITLE
 Tabs validate parent is proper tab container

### PR DESCRIPTION
**Pull request by tankztz**
### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/reflex-dev/reflex/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/reflex-dev/reflex/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### **After** these steps, you're ready to open a pull request.

    a. Give a descriptive title to your PR.

    b. Describe your changes.

    c. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by tankztz** [comment]
closes #2173

**Review by masenf — COMMENTED** [review]
is there a reason why using `_valid_children` didn't work for this case?

**Comment by tankztz** [comment]
> is there a reason why using `_valid_children` didn't work for this case?

The requirement here is: when user create a component of rx.SomeComponent(rx.TabList) we need to report error. 

`_valid_children` means "only components that are allowed as children". Adding TabList as `_valid_children` for Tabs doesn't fix the bug because the parent of TabList could be anything.

Here are two ideas: 
1. Declare TabList as invalid child for all component except Tabs - it is changing too many things
2. Declare the parent of TabList should only be Tabs - This is what I'm doing

**Comment by masenf** [comment]
What about making `TabList` and `TabPanels` and `_valid_children` of `Tabs` though? Just taking everything up a level.

**Comment by tankztz** [comment]
@masenf Any follow-ups?

**Review by masenf — APPROVED** [review]

**Review by picklelo — APPROVED** [review]
nice addition - this will be useful for our new radix components as well which have nested components like this.

**Pull request merged**
