### PR TITLE
rx.icon_button is now working

### LINKED ISSUE #1497: icon prop in `rx.icon_button`  doesnt work
icon prop should take a component. Also providing string values doesnt work

### PR DESCRIPTION
**Pull request by andrewbantly**
Previously `rx.icon_button` would not accept any props and therefore was unable to render any icons. My fix now requires two props `icon` and `aria_label`, which allows the developer to select the icon of choice and follow Web Content Accessibility Guidelines. 

I want to point out that I wasn't able to solve a potential issue in which the `aria_label` does not transformed into `aria-label` when I inspect the element in Chrome Developer Tools. Currently, the code submitted in this PR has the button property of `arialabel` when you examine the element. 

Closes #1497 

### All Submissions:

- [ x ] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md) file?
- [ x ] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/pynecone-io/pynecone/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [ x ] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by ElijahAhianyo — CHANGES_REQUESTED** [review]
@andrewbantly  Thanks for taking this up. Your implementation seems to wrap an icon component in a button component, while this may work it doesnt give the desired outcome aesthetically.  The goal is to use the provided `iconButton` component chakra gives. If you look in the rendered js output (`.web/pages/index.js`), your implementation renders as :
```js
<button ariaLabel="send email" icon="email">
  <EmailIcon/>
```
as opposed to :
```js
<IconButton
  colorScheme='blue'
  aria-label='Search database'
  icon={<SearchIcon />}
/>
```
You'd also realize that the icon prop takes in a component(could be an icon component). We want to achieve the same. Currently, it takes in a string value, this should be modified to take a component instead. Feel free to reach out if you have any questions.

**Comment by andrewbantly** [comment]
@ElijahAhianyo I believe I fixed the original issue by passing the icon component through the chakra-ui icon-button component. 

I can't figure out how to transform the `aria_label` prop into `aria-label` on the DOM. When I inspect the element in Chrome Developer Tools, `arialabel` appears. 

I'd be happy to continue working on this, but wondering if you had any suggestions?

**Comment by andrewbantly** [comment]
@ElijahAhianyo I wanted to follow up regarding my above comment. Thanks!

**Comment by masenf** [comment]
Closing stale issue since `rx.icon_button` will be changing in reflex-0.4.0

**Pull request closed without merging**
