### PR TITLE
CLI will not set auto/stop setting for deployment

### PR DESCRIPTION
**Pull request by martinxu9**
### All Submissions:

- [x] Have you followed the guidelines stated in [CONTRIBUTING.md](https://github.com/reflex-dev/reflex/blob/main/CONTRIBUTING.md) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/reflex-dev/reflex/pulls ) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### New Feature Submission:

- [x] Does your submission pass the tests? 
- [x] Have you linted your code locally prior to submission?

### Changes To Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?

### **After** these steps, you're ready to open a pull request.
- Remove the defaults from CLI side, let hosting service take control of the defaults.
- Wherever there's default, clarify "enter to use default"
- Remove "backend is up" and "frontend is up" at the end. 
- Add warning if app is taking too long, tell user about the logs command.
image

### CODE REVIEW

**Comment by Alek99** [comment]
Whats the best way to test this should I just deploy of this branch? IS the dataplane also set up to handle the no auto stop right now

**Comment by martinxu9** [comment]
> Whats the best way to test this should I just deploy of this branch? IS the dataplane also set up to handle the no auto stop right now

@Alek99 theres some outage. We can't deploy new CP. I think to test just run it to deploy. It should still deploy. Just the start/stop settings are filled in by CP. once we deploy a new CP, it'll be our desired setting

**Review by picklelo — APPROVED** [review]

**Comment by picklelo** [comment]
Waiting for testing with the control plane before merging

**Comment by Alek99** [comment]
Tested a deployment and works for me

**Pull request merged**
