### PR TITLE
upgrade node to latest lts

### PR DESCRIPTION
**Pull request by adhami3310**
nodejs 22 will reach LTS in a week from now, only merge after that happens and a new LTS release has happened (most likely 22.10.0)

https://endoflife.date/nodejs

### CODE REVIEW

**Review by Lendemor — APPROVED** [review]

**Comment by masenf** [comment]
i thought we were going to wait until tomorrow when node 22 becomes lts...

**Comment by adhami3310** [comment]
yea that was not supposed to merge, it's not breaking anything, so we can wait till tomorrow to see if any new release happens and any changes need to happen

**Comment by picklelo** [comment]
Oh my bad / shall I revert this?

**Comment by masenf** [comment]
> Oh my bad / shall I revert this?

no i think it's fine.

@adhami3310 in the future, if we have PRs that are ready and approved but shouldn't be merged yet, lets keep them as draft

**Pull request merged**
