### PR TITLE
redesign error boundary screen

### PR DESCRIPTION
**Pull request by adhami3310**

### CODE REVIEW

**Review by masenf — COMMENTED** [review]
this looks much better than the crap we had before, nice.

i think visually it might be better if it were in the top third rather than vertically centered on the page, but i'm not splitting hairs as i'm not a designer.

you should add the screenshots to the PR description and have @Alek99 / @carlosabadia take a look at it

**Comment by adhami3310** [comment]
image
image
image
image

**Comment by adhami3310** [comment]
@Alek99 @carlosabadia let me know if improvements can be made!

Note this has to be implemented in pure HTML, as we don't get Radix in the fallback place.

**Comment by adhami3310** [comment]
@masenf it doesn't seem we're getting feedback on this now, so we can merge it and redesign it later if needed

**Comment by carlosabadia** [comment]
didn't see this, sorry. Looks good to me!

**Review by masenf — APPROVED** [review]

**Pull request merged**
