### PR TITLE
use dict instead of set to store hooks

### PR DESCRIPTION
**Pull request by Lendemor**
hooks are currently stored in `set()` which do not preserve their order.
This can be problematic if a given hook A rely on another hook B but A is written before B during compilation.

By using dict we can keep the uniqueness of hooks as well as keep their order.

### CODE REVIEW

**Review by picklelo — COMMENTED** [review]
Why not use a list, if we don't have any values needed?

**Comment by masenf** [comment]
> Why not use a list

At the end of the day we need to dedupe the values anyway. We can't use a set for this because sets lose the order. So even if we keep it in a list, ultimately it will have to go through a value-less dict at some point anyway.

I guess the decision is just about the API, is it better to have the users deal with lists?

**Comment by Lendemor** [comment]
> I guess the decision is just about the API, is it better to have the users deal with lists?

I think most users will never interact with either in the end, because they will mostly define the hooks in the _underscored method returning a single hook ?

**Comment by picklelo** [comment]
Okay makes sense to me - I'm good with the dict method

**Review by picklelo — APPROVED** [review]

**Pull request merged**
